from pathlib import Path
import re
path = Path(''BSMS.WebApp/Pages/Admin/Operations/Index.cshtml'')
text = path.read_text(encoding='utf-8')
pattern = re.compile(r'''                <div class="col-md-3">\s*\n                    <label asp-for="StationStaffForm\.ShiftStart" class="form-label">.*?</label>\s*\n                    <input asp-for="StationStaffForm\.ShiftStart" class="form-control" type="time" />\s*\n                    <span asp-validation-for="StationStaffForm\.ShiftStart" class="text-danger small"></span>\s*\n                </div>\s*\n                <div class="col-md-3">\s*\n                    <label asp-for="StationStaffForm\.ShiftEnd" class="form-label">.*?</label>\s*\n                    <input asp-for="StationStaffForm\.ShiftEnd" class="form-control" type="time" />\s*\n                    <span asp-validation-for="StationStaffForm\.ShiftEnd" class="text-danger small"></span>\s*\n                </div>\s*\n                <div class="col-md-3">\s*\n                    <label asp-for="StationStaffForm\.AssignedAt" class="form-label"></label>\s*\n                    <input asp-for="StationStaffForm\.AssignedAt" class="form-control" type="datetime-local" />\s*\n                    <span asp-validation-for="StationStaffForm\.AssignedAt" class="text-danger small"></span>\s*\n                </div>''', re.MULTILINE)
new_block = '''                <div class="col-md-3">\n                    <label asp-for="StationStaffForm.ShiftStart" class="form-label">Gi? b?t d?u ca</label>\n                    <input asp-for="StationStaffForm.ShiftStart"\n                           class="form-control"\n                           type="time"\n                           min="06:00"\n                           max="22:00"\n                           step="900"\n                           data-shift-start-input="true" />\n                    <span asp-validation-for="StationStaffForm.ShiftStart" class="text-danger small"></span>\n                </div>\n                <div class="col-md-3">\n                    <label asp-for="StationStaffForm.ShiftEnd" class="form-label">Gi? k?t thúc ca</label>\n                    <input asp-for="StationStaffForm.ShiftEnd"\n                           class="form-control"\n                           type="time"\n                           min="06:00"\n                           max="22:00"\n                           step="900"\n                           data-shift-end-input="true" />\n                    <span asp-validation-for="StationStaffForm.ShiftEnd" class="text-danger small"></span>\n                </div>\n                <div class="col-md-3">\n                    <label asp-for="StationStaffForm.AssignedAt" class="form-label"></label>\n                    <input asp-for="StationStaffForm.AssignedAt"\n                           class="form-control bg-body-secondary"\n                           type="datetime-local"\n                           data-assigned-at-input="true"\n                           readonly />\n                    <div class="form-text">\n                        <div class="form-check form-switch form-switch-sm d-inline-flex align-items-center gap-2">\n                            <input class="form-check-input" type="checkbox" role="switch" id="assignedAtManualToggle" data-assigned-manual-toggle="true">\n                            <label class="form-check-label small" for="assignedAtManualToggle">Cho phép ch?nh tay</label>\n                        </div>\n                        <div class="small text-muted">M?c d?nh dùng th?i di?m hi?n t?i khi t?o m?i.</div>\n                    </div>\n                    <span asp-validation-for="StationStaffForm.AssignedAt" class="text-danger small"></span>\n                </div>\n                <div class="col-12">\n                    <div class="text-danger small d-none" data-shift-validation-message="true"></div>\n                </div>'''
new_text, count = pattern.subn(new_block, text, count=1)
if count != 1:
    raise SystemExit(f'replacement count {count}')
path.write_text(new_text, encoding='utf-8')
